export default {
  id: 'Id',
  program: 'Programa',
  subProgram: 'SubPrograma',
  name: 'Nome',
  road: 'Rodovia',
  extension: 'Extensão',
  status: 'Situação',
  startedAt: 'Ordem de Início',
  amountDone: 'Execução Financeira',
  totalEstimated: 'Valor total estimado',
  resourcesToBeAvailable: 'Recurso a Viabilizar',
  resourcesAvailable: 'Recurso Viabilizados',
  dueAt: 'Previsão de conclusão',
  cities: 'Municípios diretamente beneficiados',
  enterprises: 'Empresa contratada',
  populationEstimated: 'População beneficiada estimada',
  directJobs: 'Empregos gerados diretamente',
  indirectJobs: 'Empregos gerados indiretamente'
}
