name: CI/CD Pipeline


on:
  push:
    tags:
      - 'v*' # Trigger only for tags that start with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: "false"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Building
        run: echo Building Application


  deploy-dev:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY_DEV }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID_DEV }}

      - name: Realizando Deploy em Develop
        run: echo Deploy Application in Dev Environment

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY_PROD }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID_PROD }}

      - name: Realizando Deploy em Produção
        run: echo Deploy Application in Prd Environment

